language: bash

# for secret experimental features ;)
sudo: 9000

env:
  - VERSION=centos7

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - export image="nuocw/buildpack-deps:$VERSION"

script:
  - test "$(head -n1 Dockerfile)" = "FROM $image-scm"
    && test "$(head -n1 scm/Dockerfile)" = "FROM $image-curl"
    && test "$(head -n1 curl/Dockerfile)" == "FROM centos:$VERSION"
  - docker build -t "$image-curl" curl
  - docker build -t "$image-scm" scm
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
